package org.example;

public enum BotState {
    DEFAULT,
    ON_RULES_MSG,
    LINK_TO_TELEGRAM_CHANNEL_SENT,
    SHOPS_LINKS_SENT,
    CONTACTS_SENT,
    WEBPAGE_LINK_SENT,
ADMIN_DEFAULT,
    ADMIN_SENDDATABASE,
    ADMIN_INITIATE_SEND_MESSAGE,
    ADMIN_SEND_MESSAGE,
    ADMIN_SEND_USER_COUNTER,
    ADMIN_SET_MESSAGE_FOR_SUBS
}
